#include "address_map_nios2.h"
#include "nios2_ctrl_reg_macros.h"

/* these globals are written by interrupt service routines; we have to declare
 * these as volatile to avoid the compiler caching their values in registers */
extern volatile int record, play, buffer_index; // used for audio
extern volatile int timeout; // used to synchronize with the timer

/* function prototypes */
void VGA_text(int, int, char *);
void VGA_box(int, int, int, int, short);

/*******************************************************************************
 * This program performs the following:
 *  1. records audio for about 10 seconds when an interrupt is generated by
 *     pressing KEY[0]. LEDR[0] is lit while recording. Audio recording is
 *     controlled by using interrupts
 *  2. plays the recorded audio when an interrupt is generated by pressing
 *     KEY[1]. LEDR[1] is lit while playing. Audio playback is controlled by
 *     using interrupts
 ******************************************************************************/
int main(void) {

    /* Declare volatile pointers to I/O registers (volatile means that IO load
       and store instructions will be used to access these pointer locations,
       instead of regular memory loads and stores) */
    volatile int * interval_timer_ptr =
        (int *)TIMER_BASE;                        // interal timer base address
    volatile int * KEY_ptr   = (int *)KEY_BASE;   // pushbutton KEY address
    volatile int * audio_ptr = (int *)AUDIO_BASE; // audio port address

    /* initialize some variables */
    record       = 0;
    play         = 0;
    buffer_index = 0; // used for audio record/playback
    timeout      = 0; // synchronize with the timer

    /* set the interval timer period */
    int counter = 20000000; // 1/(100 MHz) x (20000000) = 200 msec
    *(interval_timer_ptr + 0x2) = (counter & 0xFFFF);
    *(interval_timer_ptr + 0x3) = (counter >> 16) & 0xFFFF;

    /* start interval timer, enable its interrupts */
    *(interval_timer_ptr + 1) = 0x7; // STOP = 0, START = 1, CONT = 1, ITO = 1

    *(KEY_ptr + 2) =
        0xF; /* write to the pushbutton interrupt mask register, and
              * enable interrupts on all four KEYs */

    NIOS2_WRITE_IENABLE(
        0x43); /* set interrupt mask bits for levels 0 (interval
                * timer), 1 (pushbuttons), 6 (audio) */

    NIOS2_WRITE_STATUS(1); // enable Nios II interrupts

    while (1) {
        while (!timeout)
            ; // wait to synchronize with timer

        timeout = 0;
    }
}

